version: "0.2"
ignorePaths: []
dictionaryDefinitions: []
dictionaries: []
words:
  - cdylib
  - clippy
  - codegen
  - emnapi
  - msvc
  - napi
  - nixpkgs
  - oxlint
  - pkgs
  - rustc
  - serde
  - Threadsafe
  - tybys
  - verre
ignoreWords: []
import: []
