/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Request {
  bytes(): Promise<Uint8Array | null>
  get url(): string
}
export type VerreRequest = Request

export declare class Verre {
  constructor()
  get(path: string, handler: ((err: Error | null, arg: Request) => Response)): void
  serve(): Promise<void>
}

export interface Response {
  headers?: Record<string, string>
  status?: number
  body: string
}
