/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class Request {
  bytes(): Promise<Uint8Array | null>
  get url(): string
}

export declare class Response {
  constructor()
  static text(body: string): ResponseInner
  static json(value: any): ResponseInner
}

export declare class Verre {
  constructor()
  get(path: string, handler: ((err: Error | null, arg: Request) => ResponseInner)): void
  serve(): Promise<void>
}

export interface ResponseInner {
  headers?: Record<string, string>
  status?: number
  body: string
}
